
---
- name: build an image by running ansible in a container
  hosts: myhost
  connection: local

  tasks:

    - name: install docker-py
      pip: name=docker-py state=present

    - name: build docker image - nginx with sample node app and leave it running
      docker_container:
        name: webserver
        image: richarvey/nginx-nodejs
        ports:
          - "80:80"
        detach: True
    - name: check if nginx is running
      become: True
      command: docker exec webserver /bin/sh -c "netstat -anpt|grep nginx"
      register: vagrant
    - name: proof below, that nginx is running on port 80
      debug: var=vagrant.stdout_lines

    